language: node_js
node_js:
  - '12.16.1'
before_script:
  - 'yarn'
  - 'yarn build'
script:
  - 'yarn test'
  - 'yarn coveralls'
before_deploy:
  - cd lib
deploy:
  provider: npm
  skip_cleanup: true
  email: '$EMAIL_ADDRESS'
  api_key: '$AUTH_TOKEN'
  on:
    tags: true
