language: node_js
node_js:
  - '12.16.1'
deploy:
  provider: npm
  email: '$EMAIL_ADDRESS'
  api_key: '$AUTH_TOKEN'
  on:
    tags: true
before_script:
  - 'yarn'
  - 'yarn build'
script:
  - 'yarn test'
